window.esdocSearchIndex = [
  [
    "jimpex/src/services/http/apiclient.js~apiclient",
    "class/src/services/http/apiClient.js~APIClient.html",
    "<span>APIClient</span> <span class=\"search-result-import-path\">jimpex/src/services/http/apiClient.js</span>",
    "class"
  ],
  [
    "jimpex/src/services/common/apperror.js~apperror",
    "class/src/services/common/appError.js~AppError.html",
    "<span>AppError</span> <span class=\"search-result-import-path\">jimpex/src/services/common/appError.js</span>",
    "class"
  ],
  [
    "jimpex/src/controllers/common/configuration.js~configurationcontroller",
    "class/src/controllers/common/configuration.js~ConfigurationController.html",
    "<span>ConfigurationController</span> <span class=\"search-result-import-path\">jimpex/src/controllers/common/configuration.js</span>",
    "class"
  ],
  [
    "jimpex/src/services/utils/ensurebearertoken.js~ensurebearertoken",
    "class/src/services/utils/ensureBearerToken.js~EnsureBearerToken.html",
    "<span>EnsureBearerToken</span> <span class=\"search-result-import-path\">jimpex/src/services/utils/ensureBearerToken.js</span>",
    "class"
  ],
  [
    "jimpex/src/middlewares/common/errorhandler.js~errorhandler",
    "class/src/middlewares/common/errorHandler.js~ErrorHandler.html",
    "<span>ErrorHandler</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/common/errorHandler.js</span>",
    "class"
  ],
  [
    "jimpex/src/middlewares/html/fasthtml.js~fasthtml",
    "class/src/middlewares/html/fastHTML.js~FastHTML.html",
    "<span>FastHTML</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/html/fastHTML.js</span>",
    "class"
  ],
  [
    "jimpex/src/middlewares/common/forcehttps.js~forcehttps",
    "class/src/middlewares/common/forceHTTPS.js~ForceHTTPS.html",
    "<span>ForceHTTPS</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/common/forceHTTPS.js</span>",
    "class"
  ],
  [
    "jimpex/src/services/frontend/frontendfs.js~frontendfs",
    "class/src/services/frontend/frontendFs.js~FrontendFs.html",
    "<span>FrontendFs</span> <span class=\"search-result-import-path\">jimpex/src/services/frontend/frontendFs.js</span>",
    "class"
  ],
  [
    "jimpex/src/controllers/utils/gateway.js~gatewaycontroller",
    "class/src/controllers/utils/gateway.js~GatewayController.html",
    "<span>GatewayController</span> <span class=\"search-result-import-path\">jimpex/src/controllers/utils/gateway.js</span>",
    "class"
  ],
  [
    "jimpex/src/services/html/htmlgenerator.js~htmlgenerator",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html",
    "<span>HTMLGenerator</span> <span class=\"search-result-import-path\">jimpex/src/services/html/htmlGenerator.js</span>",
    "class"
  ],
  [
    "jimpex/src/services/http/http.js~http",
    "class/src/services/http/http.js~HTTP.html",
    "<span>HTTP</span> <span class=\"search-result-import-path\">jimpex/src/services/http/http.js</span>",
    "class"
  ],
  [
    "jimpex/src/services/common/httperror.js~httperror",
    "class/src/services/common/httpError.js~HTTPError.html",
    "<span>HTTPError</span> <span class=\"search-result-import-path\">jimpex/src/services/common/httpError.js</span>",
    "class"
  ],
  [
    "jimpex/src/controllers/common/health.js~healthcontroller",
    "class/src/controllers/common/health.js~HealthController.html",
    "<span>HealthController</span> <span class=\"search-result-import-path\">jimpex/src/controllers/common/health.js</span>",
    "class"
  ],
  [
    "jimpex/src/app/index.js~jimpex",
    "class/src/app/index.js~Jimpex.html",
    "<span>Jimpex</span> <span class=\"search-result-import-path\">jimpex/src/app/index.js</span>",
    "class"
  ],
  [
    "jimpex/src/services/http/responsesbuilder.js~responsesbuilder",
    "class/src/services/http/responsesBuilder.js~ResponsesBuilder.html",
    "<span>ResponsesBuilder</span> <span class=\"search-result-import-path\">jimpex/src/services/http/responsesBuilder.js</span>",
    "class"
  ],
  [
    "jimpex/src/middlewares/html/showhtml.js~showhtml",
    "class/src/middlewares/html/showHTML.js~ShowHTML.html",
    "<span>ShowHTML</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/html/showHTML.js</span>",
    "class"
  ],
  [
    "jimpex/src/controllers/common/statics.js~staticscontroller",
    "class/src/controllers/common/statics.js~StaticsController.html",
    "<span>StaticsController</span> <span class=\"search-result-import-path\">jimpex/src/controllers/common/statics.js</span>",
    "class"
  ],
  [
    "jimpex/src/middlewares/utils/versionvalidator.js~versionvalidator",
    "class/src/middlewares/utils/versionValidator.js~VersionValidator.html",
    "<span>VersionValidator</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/utils/versionValidator.js</span>",
    "class"
  ],
  [
    "jimpex/src/services/http/apiclient.js~apiclient",
    "variable/index.html#static-variable-apiClient",
    "<span>apiClient</span> <span class=\"search-result-import-path\">jimpex/src/services/http/apiClient.js</span>",
    "variable"
  ],
  [
    "jimpex/src/services/common/apperror.js~apperror",
    "variable/index.html#static-variable-appError",
    "<span>appError</span> <span class=\"search-result-import-path\">jimpex/src/services/common/appError.js</span>",
    "variable"
  ],
  [
    "jimpex/src/services/common/index.js~commonservices",
    "variable/index.html#static-variable-commonServices",
    "<span>commonServices</span> <span class=\"search-result-import-path\">jimpex/src/services/common/index.js</span>",
    "variable"
  ],
  [
    "jimpex/src/controllers/common/configuration.js~configurationcontroller",
    "variable/index.html#static-variable-configurationController",
    "<span>configurationController</span> <span class=\"search-result-import-path\">jimpex/src/controllers/common/configuration.js</span>",
    "variable"
  ],
  [
    "jimpex/src/utils/wrappers.js~controller",
    "function/index.html#static-function-controller",
    "<span>controller</span> <span class=\"search-result-import-path\">jimpex/src/utils/wrappers.js</span>",
    "function"
  ],
  [
    "jimpex/src/utils/wrappers.js~controllercreator",
    "function/index.html#static-function-controllerCreator",
    "<span>controllerCreator</span> <span class=\"search-result-import-path\">jimpex/src/utils/wrappers.js</span>",
    "function"
  ],
  [
    "jimpex/src/utils/functions.js~createrouteexpression",
    "function/index.html#static-function-createRouteExpression",
    "<span>createRouteExpression</span> <span class=\"search-result-import-path\">jimpex/src/utils/functions.js</span>",
    "function"
  ],
  [
    "jimpex/src/services/utils/ensurebearertoken.js~ensurebearertoken",
    "variable/index.html#static-variable-ensureBearerToken",
    "<span>ensureBearerToken</span> <span class=\"search-result-import-path\">jimpex/src/services/utils/ensureBearerToken.js</span>",
    "variable"
  ],
  [
    "jimpex/src/middlewares/common/errorhandler.js~errorhandler",
    "variable/index.html#static-variable-errorHandler",
    "<span>errorHandler</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/common/errorHandler.js</span>",
    "variable"
  ],
  [
    "jimpex/src/utils/functions.js~escapeforregexp",
    "function/index.html#static-function-escapeForRegExp",
    "<span>escapeForRegExp</span> <span class=\"search-result-import-path\">jimpex/src/utils/functions.js</span>",
    "function"
  ],
  [
    "jimpex/src/constants/eventnames.js~eventnames",
    "variable/index.html#static-variable-eventNames",
    "<span>eventNames</span> <span class=\"search-result-import-path\">jimpex/src/constants/eventNames.js</span>",
    "variable"
  ],
  [
    "jimpex/src/middlewares/html/fasthtml.js~fasthtml",
    "variable/index.html#static-variable-fastHTML",
    "<span>fastHTML</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/html/fastHTML.js</span>",
    "variable"
  ],
  [
    "jimpex/src/middlewares/common/forcehttps.js~forcehttps",
    "variable/index.html#static-variable-forceHTTPS",
    "<span>forceHTTPS</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/common/forceHTTPS.js</span>",
    "variable"
  ],
  [
    "jimpex/src/services/frontend/frontendfs.js~frontendfs",
    "variable/index.html#static-variable-frontendFs",
    "<span>frontendFs</span> <span class=\"search-result-import-path\">jimpex/src/services/frontend/frontendFs.js</span>",
    "variable"
  ],
  [
    "jimpex/src/controllers/utils/gateway.js~gatewaycontroller",
    "variable/index.html#static-variable-gatewayController",
    "<span>gatewayController</span> <span class=\"search-result-import-path\">jimpex/src/controllers/utils/gateway.js</span>",
    "variable"
  ],
  [
    "jimpex/src/controllers/common/health.js~healthcontroller",
    "variable/index.html#static-variable-healthController",
    "<span>healthController</span> <span class=\"search-result-import-path\">jimpex/src/controllers/common/health.js</span>",
    "variable"
  ],
  [
    "jimpex/src/services/html/htmlgenerator.js~htmlgenerator",
    "variable/index.html#static-variable-htmlGenerator",
    "<span>htmlGenerator</span> <span class=\"search-result-import-path\">jimpex/src/services/html/htmlGenerator.js</span>",
    "variable"
  ],
  [
    "jimpex/src/services/http/http.js~http",
    "variable/index.html#static-variable-http",
    "<span>http</span> <span class=\"search-result-import-path\">jimpex/src/services/http/http.js</span>",
    "variable"
  ],
  [
    "jimpex/src/services/common/httperror.js~httperror",
    "variable/index.html#static-variable-httpError",
    "<span>httpError</span> <span class=\"search-result-import-path\">jimpex/src/services/common/httpError.js</span>",
    "variable"
  ],
  [
    "jimpex/src/services/http/index.js~httpservices",
    "variable/index.html#static-variable-httpServices",
    "<span>httpServices</span> <span class=\"search-result-import-path\">jimpex/src/services/http/index.js</span>",
    "variable"
  ],
  [
    "jimpex/src/utils/wrappers.js~middleware",
    "function/index.html#static-function-middleware",
    "<span>middleware</span> <span class=\"search-result-import-path\">jimpex/src/utils/wrappers.js</span>",
    "function"
  ],
  [
    "jimpex/src/utils/wrappers.js~middlewarecreator",
    "function/index.html#static-function-middlewareCreator",
    "<span>middlewareCreator</span> <span class=\"search-result-import-path\">jimpex/src/utils/wrappers.js</span>",
    "function"
  ],
  [
    "jimpex/src/utils/wrappers.js~provider",
    "function/index.html#static-function-provider",
    "<span>provider</span> <span class=\"search-result-import-path\">jimpex/src/utils/wrappers.js</span>",
    "function"
  ],
  [
    "jimpex/src/utils/wrappers.js~providercreator",
    "function/index.html#static-function-providerCreator",
    "<span>providerCreator</span> <span class=\"search-result-import-path\">jimpex/src/utils/wrappers.js</span>",
    "function"
  ],
  [
    "jimpex/src/utils/wrappers.js~providers",
    "function/index.html#static-function-providers",
    "<span>providers</span> <span class=\"search-result-import-path\">jimpex/src/utils/wrappers.js</span>",
    "function"
  ],
  [
    "jimpex/src/utils/functions.js~removeleadingslash",
    "function/index.html#static-function-removeLeadingSlash",
    "<span>removeLeadingSlash</span> <span class=\"search-result-import-path\">jimpex/src/utils/functions.js</span>",
    "function"
  ],
  [
    "jimpex/src/utils/functions.js~removeslashes",
    "function/index.html#static-function-removeSlashes",
    "<span>removeSlashes</span> <span class=\"search-result-import-path\">jimpex/src/utils/functions.js</span>",
    "function"
  ],
  [
    "jimpex/src/utils/functions.js~removetrailingslash",
    "function/index.html#static-function-removeTrailingSlash",
    "<span>removeTrailingSlash</span> <span class=\"search-result-import-path\">jimpex/src/utils/functions.js</span>",
    "function"
  ],
  [
    "jimpex/src/services/http/responsesbuilder.js~responsesbuilder",
    "variable/index.html#static-variable-responsesBuilder",
    "<span>responsesBuilder</span> <span class=\"search-result-import-path\">jimpex/src/services/http/responsesBuilder.js</span>",
    "variable"
  ],
  [
    "jimpex/src/services/common/sendfile.js~sendfile",
    "function/index.html#static-function-sendFile",
    "<span>sendFile</span> <span class=\"search-result-import-path\">jimpex/src/services/common/sendFile.js</span>",
    "function"
  ],
  [
    "jimpex/src/services/common/sendfile.js~sendfileprovider",
    "variable/index.html#static-variable-sendFileProvider",
    "<span>sendFileProvider</span> <span class=\"search-result-import-path\">jimpex/src/services/common/sendFile.js</span>",
    "variable"
  ],
  [
    "jimpex/src/middlewares/html/showhtml.js~showhtml",
    "variable/index.html#static-variable-showHTML",
    "<span>showHTML</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/html/showHTML.js</span>",
    "variable"
  ],
  [
    "jimpex/src/controllers/common/statics.js~staticscontroller",
    "variable/index.html#static-variable-staticsController",
    "<span>staticsController</span> <span class=\"search-result-import-path\">jimpex/src/controllers/common/statics.js</span>",
    "variable"
  ],
  [
    "jimpex/src/services/utils/index.js~utilsservices",
    "variable/index.html#static-variable-utilsServices",
    "<span>utilsServices</span> <span class=\"search-result-import-path\">jimpex/src/services/utils/index.js</span>",
    "variable"
  ],
  [
    "jimpex/src/middlewares/utils/versionvalidator.js~versionvalidator",
    "variable/index.html#static-variable-versionValidator",
    "<span>versionValidator</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/utils/versionValidator.js</span>",
    "variable"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/app/index.js",
    "file/src/app/index.js.html",
    "src/app/index.js",
    "file"
  ],
  [
    "src/app/index.js~jimpex#_emitevent",
    "class/src/app/index.js~Jimpex.html#instance-method-_emitEvent",
    "src/app/index.js~Jimpex#_emitEvent",
    "method"
  ],
  [
    "src/app/index.js~jimpex#_reducewithevent",
    "class/src/app/index.js~Jimpex.html#instance-method-_reduceWithEvent",
    "src/app/index.js~Jimpex#_reduceWithEvent",
    "method"
  ],
  [
    "src/app/index.js~jimpex#boot",
    "class/src/app/index.js~Jimpex.html#instance-method-boot",
    "src/app/index.js~Jimpex#boot",
    "method"
  ],
  [
    "src/app/index.js~jimpex#constructor",
    "class/src/app/index.js~Jimpex.html#instance-constructor-constructor",
    "src/app/index.js~Jimpex#constructor",
    "method"
  ],
  [
    "src/app/index.js~jimpex#disabletlsvalidation",
    "class/src/app/index.js~Jimpex.html#instance-method-disableTLSValidation",
    "src/app/index.js~Jimpex#disableTLSValidation",
    "method"
  ],
  [
    "src/app/index.js~jimpex#express",
    "class/src/app/index.js~Jimpex.html#instance-get-express",
    "src/app/index.js~Jimpex#express",
    "member"
  ],
  [
    "src/app/index.js~jimpex#instance",
    "class/src/app/index.js~Jimpex.html#instance-get-instance",
    "src/app/index.js~Jimpex#instance",
    "member"
  ],
  [
    "src/app/index.js~jimpex#listen",
    "class/src/app/index.js~Jimpex.html#instance-method-listen",
    "src/app/index.js~Jimpex#listen",
    "method"
  ],
  [
    "src/app/index.js~jimpex#mount",
    "class/src/app/index.js~Jimpex.html#instance-method-mount",
    "src/app/index.js~Jimpex#mount",
    "method"
  ],
  [
    "src/app/index.js~jimpex#options",
    "class/src/app/index.js~Jimpex.html#instance-get-options",
    "src/app/index.js~Jimpex#options",
    "member"
  ],
  [
    "src/app/index.js~jimpex#routes",
    "class/src/app/index.js~Jimpex.html#instance-get-routes",
    "src/app/index.js~Jimpex#routes",
    "member"
  ],
  [
    "src/app/index.js~jimpex#start",
    "class/src/app/index.js~Jimpex.html#instance-method-start",
    "src/app/index.js~Jimpex#start",
    "method"
  ],
  [
    "src/app/index.js~jimpex#stop",
    "class/src/app/index.js~Jimpex.html#instance-method-stop",
    "src/app/index.js~Jimpex#stop",
    "method"
  ],
  [
    "src/app/index.js~jimpex#try",
    "class/src/app/index.js~Jimpex.html#instance-method-try",
    "src/app/index.js~Jimpex#try",
    "method"
  ],
  [
    "src/app/index.js~jimpex#use",
    "class/src/app/index.js~Jimpex.html#instance-method-use",
    "src/app/index.js~Jimpex#use",
    "method"
  ],
  [
    "src/app/typedef.js",
    "file/src/app/typedef.js.html",
    "src/app/typedef.js",
    "file"
  ],
  [
    "src/app/typedef.js~jimpexconfigurationoptions",
    "typedef/index.html#static-typedef-JimpexConfigurationOptions",
    "src/app/typedef.js~JimpexConfigurationOptions",
    "typedef"
  ],
  [
    "src/app/typedef.js~jimpexdefaultservicesoptions",
    "typedef/index.html#static-typedef-JimpexDefaultServicesOptions",
    "src/app/typedef.js~JimpexDefaultServicesOptions",
    "typedef"
  ],
  [
    "src/app/typedef.js~jimpexexpressoptions",
    "typedef/index.html#static-typedef-JimpexExpressOptions",
    "src/app/typedef.js~JimpexExpressOptions",
    "typedef"
  ],
  [
    "src/app/typedef.js~jimpexoptions",
    "typedef/index.html#static-typedef-JimpexOptions",
    "src/app/typedef.js~JimpexOptions",
    "typedef"
  ],
  [
    "src/app/typedef.js~jimpexstaticsoptions",
    "typedef/index.html#static-typedef-JimpexStaticsOptions",
    "src/app/typedef.js~JimpexStaticsOptions",
    "typedef"
  ],
  [
    "src/app/typedef.js~jimple",
    "https://yarnpkg.com/en/package/jimple",
    "src/app/typedef.js~Jimple",
    "external"
  ],
  [
    "src/constants/eventnames.js",
    "file/src/constants/eventNames.js.html",
    "src/constants/eventNames.js",
    "file"
  ],
  [
    "src/constants/eventnames.js~jimpexevents",
    "typedef/index.html#static-typedef-JimpexEvents",
    "src/constants/eventNames.js~JimpexEvents",
    "typedef"
  ],
  [
    "src/constants/index.js",
    "file/src/constants/index.js.html",
    "src/constants/index.js",
    "file"
  ],
  [
    "src/controllers/common/configuration.js",
    "file/src/controllers/common/configuration.js.html",
    "src/controllers/common/configuration.js",
    "file"
  ],
  [
    "src/controllers/common/configuration.js~configurationcontroller#constructor",
    "class/src/controllers/common/configuration.js~ConfigurationController.html#instance-constructor-constructor",
    "src/controllers/common/configuration.js~ConfigurationController#constructor",
    "method"
  ],
  [
    "src/controllers/common/configuration.js~configurationcontroller#getconfigurationresponse",
    "class/src/controllers/common/configuration.js~ConfigurationController.html#instance-method-getConfigurationResponse",
    "src/controllers/common/configuration.js~ConfigurationController#getConfigurationResponse",
    "method"
  ],
  [
    "src/controllers/common/configuration.js~configurationcontroller#showconfiguration",
    "class/src/controllers/common/configuration.js~ConfigurationController.html#instance-method-showConfiguration",
    "src/controllers/common/configuration.js~ConfigurationController#showConfiguration",
    "method"
  ],
  [
    "src/controllers/common/configuration.js~configurationcontroller#switchconfiguration",
    "class/src/controllers/common/configuration.js~ConfigurationController.html#instance-method-switchConfiguration",
    "src/controllers/common/configuration.js~ConfigurationController#switchConfiguration",
    "method"
  ],
  [
    "src/controllers/common/health.js",
    "file/src/controllers/common/health.js.html",
    "src/controllers/common/health.js",
    "file"
  ],
  [
    "src/controllers/common/health.js~healthcontroller#constructor",
    "class/src/controllers/common/health.js~HealthController.html#instance-constructor-constructor",
    "src/controllers/common/health.js~HealthController#constructor",
    "method"
  ],
  [
    "src/controllers/common/health.js~healthcontroller#health",
    "class/src/controllers/common/health.js~HealthController.html#instance-method-health",
    "src/controllers/common/health.js~HealthController#health",
    "method"
  ],
  [
    "src/controllers/common/index.js",
    "file/src/controllers/common/index.js.html",
    "src/controllers/common/index.js",
    "file"
  ],
  [
    "src/controllers/common/statics.js",
    "file/src/controllers/common/statics.js.html",
    "src/controllers/common/statics.js",
    "file"
  ],
  [
    "src/controllers/common/statics.js~staticscontroller#addroutes",
    "class/src/controllers/common/statics.js~StaticsController.html#instance-method-addRoutes",
    "src/controllers/common/statics.js~StaticsController#addRoutes",
    "method"
  ],
  [
    "src/controllers/common/statics.js~staticscontroller#constructor",
    "class/src/controllers/common/statics.js~StaticsController.html#instance-constructor-constructor",
    "src/controllers/common/statics.js~StaticsController#constructor",
    "method"
  ],
  [
    "src/controllers/common/statics.js~staticscontroller#options",
    "class/src/controllers/common/statics.js~StaticsController.html#instance-get-options",
    "src/controllers/common/statics.js~StaticsController#options",
    "member"
  ],
  [
    "src/controllers/common/statics.js~staticscontrollerpathsoptions",
    "typedef/index.html#static-typedef-StaticsControllerPathsOptions",
    "src/controllers/common/statics.js~StaticsControllerPathsOptions",
    "typedef"
  ],
  [
    "src/controllers/index.js",
    "file/src/controllers/index.js.html",
    "src/controllers/index.js",
    "file"
  ],
  [
    "src/controllers/utils/gateway.js",
    "file/src/controllers/utils/gateway.js.html",
    "src/controllers/utils/gateway.js",
    "file"
  ],
  [
    "src/controllers/utils/gateway.js~gatewayconfiguration",
    "typedef/index.html#static-typedef-GatewayConfiguration",
    "src/controllers/utils/gateway.js~GatewayConfiguration",
    "typedef"
  ],
  [
    "src/controllers/utils/gateway.js~gatewayconfigurationendpoint",
    "typedef/index.html#static-typedef-GatewayConfigurationEndpoint",
    "src/controllers/utils/gateway.js~GatewayConfigurationEndpoint",
    "typedef"
  ],
  [
    "src/controllers/utils/gateway.js~gatewayconfigurationendpoints",
    "typedef/index.html#static-typedef-GatewayConfigurationEndpoints",
    "src/controllers/utils/gateway.js~GatewayConfigurationEndpoints",
    "typedef"
  ],
  [
    "src/controllers/utils/gateway.js~gatewaycontroller#_apiclientconfiguration",
    "class/src/controllers/utils/gateway.js~GatewayController.html#instance-member-_apiClientConfiguration",
    "src/controllers/utils/gateway.js~GatewayController#_apiClientConfiguration",
    "member"
  ],
  [
    "src/controllers/utils/gateway.js~gatewaycontroller#_helperservice",
    "class/src/controllers/utils/gateway.js~GatewayController.html#instance-member-_helperService",
    "src/controllers/utils/gateway.js~GatewayController#_helperService",
    "member"
  ],
  [
    "src/controllers/utils/gateway.js~gatewaycontroller#addroutes",
    "class/src/controllers/utils/gateway.js~GatewayController.html#instance-method-addRoutes",
    "src/controllers/utils/gateway.js~GatewayController#addRoutes",
    "method"
  ],
  [
    "src/controllers/utils/gateway.js~gatewaycontroller#constructor",
    "class/src/controllers/utils/gateway.js~GatewayController.html#instance-constructor-constructor",
    "src/controllers/utils/gateway.js~GatewayController#constructor",
    "method"
  ],
  [
    "src/controllers/utils/gateway.js~gatewaycontroller#endpointsforapiclient",
    "class/src/controllers/utils/gateway.js~GatewayController.html#instance-get-endpointsForAPIClient",
    "src/controllers/utils/gateway.js~GatewayController#endpointsForAPIClient",
    "member"
  ],
  [
    "src/controllers/utils/gateway.js~gatewaycontroller#gatewayconfig",
    "class/src/controllers/utils/gateway.js~GatewayController.html#instance-get-gatewayConfig",
    "src/controllers/utils/gateway.js~GatewayController#gatewayConfig",
    "member"
  ],
  [
    "src/controllers/utils/gateway.js~gatewaycontroller#options",
    "class/src/controllers/utils/gateway.js~GatewayController.html#instance-get-options",
    "src/controllers/utils/gateway.js~GatewayController#options",
    "member"
  ],
  [
    "src/controllers/utils/gateway.js~gatewaycontrollercreatoroptions",
    "typedef/index.html#static-typedef-GatewayControllerCreatorOptions",
    "src/controllers/utils/gateway.js~GatewayControllerCreatorOptions",
    "typedef"
  ],
  [
    "src/controllers/utils/gateway.js~gatewaycontrollerendpointinformation",
    "typedef/index.html#static-typedef-GatewayControllerEndpointInformation",
    "src/controllers/utils/gateway.js~GatewayControllerEndpointInformation",
    "typedef"
  ],
  [
    "src/controllers/utils/gateway.js~gatewaycontrollerheadersoptions",
    "typedef/index.html#static-typedef-GatewayControllerHeadersOptions",
    "src/controllers/utils/gateway.js~GatewayControllerHeadersOptions",
    "typedef"
  ],
  [
    "src/controllers/utils/gateway.js~gatewaycontrolleroptions",
    "typedef/index.html#static-typedef-GatewayControllerOptions",
    "src/controllers/utils/gateway.js~GatewayControllerOptions",
    "typedef"
  ],
  [
    "src/controllers/utils/gateway.js~gatewaycontrollerrequest",
    "typedef/index.html#static-typedef-GatewayControllerRequest",
    "src/controllers/utils/gateway.js~GatewayControllerRequest",
    "typedef"
  ],
  [
    "src/controllers/utils/gateway.js~gatewayhelperservice",
    "typedef/index.html#static-typedef-GatewayHelperService",
    "src/controllers/utils/gateway.js~GatewayHelperService",
    "typedef"
  ],
  [
    "src/controllers/utils/gateway.js~gatewayhelperserviceerrorhandler",
    "typedef/index.html#static-typedef-GatewayHelperServiceErrorHandler",
    "src/controllers/utils/gateway.js~GatewayHelperServiceErrorHandler",
    "typedef"
  ],
  [
    "src/controllers/utils/gateway.js~gatewayhelperservicerequestreducer",
    "typedef/index.html#static-typedef-GatewayHelperServiceRequestReducer",
    "src/controllers/utils/gateway.js~GatewayHelperServiceRequestReducer",
    "typedef"
  ],
  [
    "src/controllers/utils/gateway.js~gatewayhelperserviceresponsehandler",
    "typedef/index.html#static-typedef-GatewayHelperServiceResponseHandler",
    "src/controllers/utils/gateway.js~GatewayHelperServiceResponseHandler",
    "typedef"
  ],
  [
    "src/controllers/utils/gateway.js~gatewayhelperserviceresponsereducer",
    "typedef/index.html#static-typedef-GatewayHelperServiceResponseReducer",
    "src/controllers/utils/gateway.js~GatewayHelperServiceResponseReducer",
    "typedef"
  ],
  [
    "src/controllers/utils/gateway.js~gatewayhelperservicestreamverification",
    "typedef/index.html#static-typedef-GatewayHelperServiceStreamVerification",
    "src/controllers/utils/gateway.js~GatewayHelperServiceStreamVerification",
    "typedef"
  ],
  [
    "src/controllers/utils/index.js",
    "file/src/controllers/utils/index.js.html",
    "src/controllers/utils/index.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/middlewares/common/errorhandler.js",
    "file/src/middlewares/common/errorHandler.js.html",
    "src/middlewares/common/errorHandler.js",
    "file"
  ],
  [
    "src/middlewares/common/errorhandler.js~errorhandler#constructor",
    "class/src/middlewares/common/errorHandler.js~ErrorHandler.html#instance-constructor-constructor",
    "src/middlewares/common/errorHandler.js~ErrorHandler#constructor",
    "method"
  ],
  [
    "src/middlewares/common/errorhandler.js~errorhandler#middleware",
    "class/src/middlewares/common/errorHandler.js~ErrorHandler.html#instance-method-middleware",
    "src/middlewares/common/errorHandler.js~ErrorHandler#middleware",
    "method"
  ],
  [
    "src/middlewares/common/errorhandler.js~errorhandler#options",
    "class/src/middlewares/common/errorHandler.js~ErrorHandler.html#instance-get-options",
    "src/middlewares/common/errorHandler.js~ErrorHandler#options",
    "member"
  ],
  [
    "src/middlewares/common/errorhandler.js~errorhandlerdefaultoptions",
    "typedef/index.html#static-typedef-ErrorHandlerDefaultOptions",
    "src/middlewares/common/errorHandler.js~ErrorHandlerDefaultOptions",
    "typedef"
  ],
  [
    "src/middlewares/common/errorhandler.js~errorhandleroptions",
    "typedef/index.html#static-typedef-ErrorHandlerOptions",
    "src/middlewares/common/errorHandler.js~ErrorHandlerOptions",
    "typedef"
  ],
  [
    "src/middlewares/common/forcehttps.js",
    "file/src/middlewares/common/forceHTTPS.js.html",
    "src/middlewares/common/forceHTTPS.js",
    "file"
  ],
  [
    "src/middlewares/common/forcehttps.js~forcehttps#constructor",
    "class/src/middlewares/common/forceHTTPS.js~ForceHTTPS.html#instance-constructor-constructor",
    "src/middlewares/common/forceHTTPS.js~ForceHTTPS#constructor",
    "method"
  ],
  [
    "src/middlewares/common/forcehttps.js~forcehttps#ignoredroutes",
    "class/src/middlewares/common/forceHTTPS.js~ForceHTTPS.html#instance-get-ignoredRoutes",
    "src/middlewares/common/forceHTTPS.js~ForceHTTPS#ignoredRoutes",
    "member"
  ],
  [
    "src/middlewares/common/forcehttps.js~forcehttps#middleware",
    "class/src/middlewares/common/forceHTTPS.js~ForceHTTPS.html#instance-method-middleware",
    "src/middlewares/common/forceHTTPS.js~ForceHTTPS#middleware",
    "method"
  ],
  [
    "src/middlewares/common/index.js",
    "file/src/middlewares/common/index.js.html",
    "src/middlewares/common/index.js",
    "file"
  ],
  [
    "src/middlewares/html/fasthtml.js",
    "file/src/middlewares/html/fastHTML.js.html",
    "src/middlewares/html/fastHTML.js",
    "file"
  ],
  [
    "src/middlewares/html/fasthtml.js~fasthtml#_options",
    "class/src/middlewares/html/fastHTML.js~FastHTML.html#instance-member-_options",
    "src/middlewares/html/fastHTML.js~FastHTML#_options",
    "member"
  ],
  [
    "src/middlewares/html/fasthtml.js~fasthtml#constructor",
    "class/src/middlewares/html/fastHTML.js~FastHTML.html#instance-constructor-constructor",
    "src/middlewares/html/fastHTML.js~FastHTML#constructor",
    "method"
  ],
  [
    "src/middlewares/html/fasthtml.js~fasthtml#middleware",
    "class/src/middlewares/html/fastHTML.js~FastHTML.html#instance-method-middleware",
    "src/middlewares/html/fastHTML.js~FastHTML#middleware",
    "method"
  ],
  [
    "src/middlewares/html/fasthtml.js~fasthtml#options",
    "class/src/middlewares/html/fastHTML.js~FastHTML.html#instance-get-options",
    "src/middlewares/html/fastHTML.js~FastHTML#options",
    "member"
  ],
  [
    "src/middlewares/html/fasthtml.js~fasthtmlmiddlewareoptions",
    "typedef/index.html#static-typedef-FastHTMLMiddlewareOptions",
    "src/middlewares/html/fastHTML.js~FastHTMLMiddlewareOptions",
    "typedef"
  ],
  [
    "src/middlewares/html/fasthtml.js~fasthtmloptions",
    "typedef/index.html#static-typedef-FastHTMLOptions",
    "src/middlewares/html/fastHTML.js~FastHTMLOptions",
    "typedef"
  ],
  [
    "src/middlewares/html/index.js",
    "file/src/middlewares/html/index.js.html",
    "src/middlewares/html/index.js",
    "file"
  ],
  [
    "src/middlewares/html/showhtml.js",
    "file/src/middlewares/html/showHTML.js.html",
    "src/middlewares/html/showHTML.js",
    "file"
  ],
  [
    "src/middlewares/html/showhtml.js~showhtml#constructor",
    "class/src/middlewares/html/showHTML.js~ShowHTML.html#instance-constructor-constructor",
    "src/middlewares/html/showHTML.js~ShowHTML#constructor",
    "method"
  ],
  [
    "src/middlewares/html/showhtml.js~showhtml#file",
    "class/src/middlewares/html/showHTML.js~ShowHTML.html#instance-get-file",
    "src/middlewares/html/showHTML.js~ShowHTML#file",
    "member"
  ],
  [
    "src/middlewares/html/showhtml.js~showhtml#middleware",
    "class/src/middlewares/html/showHTML.js~ShowHTML.html#instance-method-middleware",
    "src/middlewares/html/showHTML.js~ShowHTML#middleware",
    "method"
  ],
  [
    "src/middlewares/html/showhtml.js~showhtmlmiddlewareoptions",
    "typedef/index.html#static-typedef-ShowHTMLMiddlewareOptions",
    "src/middlewares/html/showHTML.js~ShowHTMLMiddlewareOptions",
    "typedef"
  ],
  [
    "src/middlewares/index.js",
    "file/src/middlewares/index.js.html",
    "src/middlewares/index.js",
    "file"
  ],
  [
    "src/middlewares/utils/index.js",
    "file/src/middlewares/utils/index.js.html",
    "src/middlewares/utils/index.js",
    "file"
  ],
  [
    "src/middlewares/utils/versionvalidator.js",
    "file/src/middlewares/utils/versionValidator.js.html",
    "src/middlewares/utils/versionValidator.js",
    "file"
  ],
  [
    "src/middlewares/utils/versionvalidator.js~versionvalidator#constructor",
    "class/src/middlewares/utils/versionValidator.js~VersionValidator.html#instance-constructor-constructor",
    "src/middlewares/utils/versionValidator.js~VersionValidator#constructor",
    "method"
  ],
  [
    "src/middlewares/utils/versionvalidator.js~versionvalidator#middleware",
    "class/src/middlewares/utils/versionValidator.js~VersionValidator.html#instance-method-middleware",
    "src/middlewares/utils/versionValidator.js~VersionValidator#middleware",
    "method"
  ],
  [
    "src/middlewares/utils/versionvalidator.js~versionvalidator#options",
    "class/src/middlewares/utils/versionValidator.js~VersionValidator.html#instance-get-options",
    "src/middlewares/utils/versionValidator.js~VersionValidator#options",
    "member"
  ],
  [
    "src/middlewares/utils/versionvalidator.js~versionvalidatoroptions",
    "typedef/index.html#static-typedef-VersionValidatorOptions",
    "src/middlewares/utils/versionValidator.js~VersionValidatorOptions",
    "typedef"
  ],
  [
    "src/services/common/apperror.js",
    "file/src/services/common/appError.js.html",
    "src/services/common/appError.js",
    "file"
  ],
  [
    "src/services/common/apperror.js~apperror#_context",
    "class/src/services/common/appError.js~AppError.html#instance-member-_context",
    "src/services/common/appError.js~AppError#_context",
    "member"
  ],
  [
    "src/services/common/apperror.js~apperror#_date",
    "class/src/services/common/appError.js~AppError.html#instance-member-_date",
    "src/services/common/appError.js~AppError#_date",
    "member"
  ],
  [
    "src/services/common/apperror.js~apperror#constructor",
    "class/src/services/common/appError.js~AppError.html#instance-constructor-constructor",
    "src/services/common/appError.js~AppError#constructor",
    "method"
  ],
  [
    "src/services/common/apperror.js~apperror#context",
    "class/src/services/common/appError.js~AppError.html#instance-get-context",
    "src/services/common/appError.js~AppError#context",
    "member"
  ],
  [
    "src/services/common/apperror.js~apperror#date",
    "class/src/services/common/appError.js~AppError.html#instance-get-date",
    "src/services/common/appError.js~AppError#date",
    "member"
  ],
  [
    "src/services/common/apperror.js~apperror#response",
    "class/src/services/common/appError.js~AppError.html#instance-get-response",
    "src/services/common/appError.js~AppError#response",
    "member"
  ],
  [
    "src/services/common/apperror.js~apperror#status",
    "class/src/services/common/appError.js~AppError.html#instance-get-status",
    "src/services/common/appError.js~AppError#status",
    "member"
  ],
  [
    "src/services/common/httperror.js",
    "file/src/services/common/httpError.js.html",
    "src/services/common/httpError.js",
    "file"
  ],
  [
    "src/services/common/httperror.js~httperror#constructor",
    "class/src/services/common/httpError.js~HTTPError.html#instance-constructor-constructor",
    "src/services/common/httpError.js~HTTPError#constructor",
    "method"
  ],
  [
    "src/services/common/index.js",
    "file/src/services/common/index.js.html",
    "src/services/common/index.js",
    "file"
  ],
  [
    "src/services/common/sendfile.js",
    "file/src/services/common/sendFile.js.html",
    "src/services/common/sendFile.js",
    "file"
  ],
  [
    "src/services/common/sendfile.js~sendfile",
    "typedef/index.html#static-typedef-SendFile",
    "src/services/common/sendFile.js~SendFile",
    "typedef"
  ],
  [
    "src/services/frontend/frontendfs.js",
    "file/src/services/frontend/frontendFs.js.html",
    "src/services/frontend/frontendFs.js",
    "file"
  ],
  [
    "src/services/frontend/frontendfs.js~frontendfs#constructor",
    "class/src/services/frontend/frontendFs.js~FrontendFs.html#instance-constructor-constructor",
    "src/services/frontend/frontendFs.js~FrontendFs#constructor",
    "method"
  ],
  [
    "src/services/frontend/frontendfs.js~frontendfs#delete",
    "class/src/services/frontend/frontendFs.js~FrontendFs.html#instance-method-delete",
    "src/services/frontend/frontendFs.js~FrontendFs#delete",
    "method"
  ],
  [
    "src/services/frontend/frontendfs.js~frontendfs#read",
    "class/src/services/frontend/frontendFs.js~FrontendFs.html#instance-method-read",
    "src/services/frontend/frontendFs.js~FrontendFs#read",
    "method"
  ],
  [
    "src/services/frontend/frontendfs.js~frontendfs#write",
    "class/src/services/frontend/frontendFs.js~FrontendFs.html#instance-method-write",
    "src/services/frontend/frontendFs.js~FrontendFs#write",
    "method"
  ],
  [
    "src/services/frontend/index.js",
    "file/src/services/frontend/index.js.html",
    "src/services/frontend/index.js",
    "file"
  ],
  [
    "src/services/html/htmlgenerator.js",
    "file/src/services/html/htmlGenerator.js.html",
    "src/services/html/htmlGenerator.js",
    "file"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgenerator#_options",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html#instance-member-_options",
    "src/services/html/htmlGenerator.js~HTMLGenerator#_options",
    "member"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgenerator#constructor",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html#instance-constructor-constructor",
    "src/services/html/htmlGenerator.js~HTMLGenerator#constructor",
    "method"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgenerator#generatehtml",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html#instance-method-generateHTML",
    "src/services/html/htmlGenerator.js~HTMLGenerator#generateHTML",
    "method"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgenerator#getfile",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html#instance-method-getFile",
    "src/services/html/htmlGenerator.js~HTMLGenerator#getFile",
    "method"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgenerator#getvalues",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html#instance-method-getValues",
    "src/services/html/htmlGenerator.js~HTMLGenerator#getValues",
    "method"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgenerator#options",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html#instance-get-options",
    "src/services/html/htmlGenerator.js~HTMLGenerator#options",
    "member"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgenerator#whenready",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html#instance-method-whenReady",
    "src/services/html/htmlGenerator.js~HTMLGenerator#whenReady",
    "method"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgeneratoroptions",
    "typedef/index.html#static-typedef-HTMLGeneratorOptions",
    "src/services/html/htmlGenerator.js~HTMLGeneratorOptions",
    "typedef"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgeneratorprovideroptions",
    "typedef/index.html#static-typedef-HTMLGeneratorProviderOptions",
    "src/services/html/htmlGenerator.js~HTMLGeneratorProviderOptions",
    "typedef"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgeneratorvaluesservice",
    "typedef/index.html#static-typedef-HTMLGeneratorValuesService",
    "src/services/html/htmlGenerator.js~HTMLGeneratorValuesService",
    "typedef"
  ],
  [
    "src/services/html/index.js",
    "file/src/services/html/index.js.html",
    "src/services/html/index.js",
    "file"
  ],
  [
    "src/services/http/apiclient.js",
    "file/src/services/http/apiClient.js.html",
    "src/services/http/apiClient.js",
    "file"
  ],
  [
    "src/services/http/apiclient.js~apiclient#apiconfig",
    "class/src/services/http/apiClient.js~APIClient.html#instance-get-apiConfig",
    "src/services/http/apiClient.js~APIClient#apiConfig",
    "member"
  ],
  [
    "src/services/http/apiclient.js~apiclient#constructor",
    "class/src/services/http/apiClient.js~APIClient.html#instance-constructor-constructor",
    "src/services/http/apiClient.js~APIClient#constructor",
    "method"
  ],
  [
    "src/services/http/apiclient.js~apiclient#error",
    "class/src/services/http/apiClient.js~APIClient.html#instance-method-error",
    "src/services/http/apiClient.js~APIClient#error",
    "method"
  ],
  [
    "src/services/http/apiclient.js~apiclient#geterrormessagefromresponse",
    "class/src/services/http/apiClient.js~APIClient.html#instance-method-getErrorMessageFromResponse",
    "src/services/http/apiClient.js~APIClient#getErrorMessageFromResponse",
    "method"
  ],
  [
    "src/services/http/apiclient.js~apiclientconfiguration",
    "typedef/index.html#static-typedef-APIClientConfiguration",
    "src/services/http/apiClient.js~APIClientConfiguration",
    "typedef"
  ],
  [
    "src/services/http/http.js",
    "file/src/services/http/http.js.html",
    "src/services/http/http.js",
    "file"
  ],
  [
    "src/services/http/http.js~http#_logrequest",
    "class/src/services/http/http.js~HTTP.html#instance-method-_logRequest",
    "src/services/http/http.js~HTTP#_logRequest",
    "method"
  ],
  [
    "src/services/http/http.js~http#_logresponse",
    "class/src/services/http/http.js~HTTP.html#instance-method-_logResponse",
    "src/services/http/http.js~HTTP#_logResponse",
    "method"
  ],
  [
    "src/services/http/http.js~http#constructor",
    "class/src/services/http/http.js~HTTP.html#instance-constructor-constructor",
    "src/services/http/http.js~HTTP#constructor",
    "method"
  ],
  [
    "src/services/http/http.js~http#fetch",
    "class/src/services/http/http.js~HTTP.html#instance-method-fetch",
    "src/services/http/http.js~HTTP#fetch",
    "method"
  ],
  [
    "src/services/http/http.js~http#getcustomheadersfromrequest",
    "class/src/services/http/http.js~HTTP.html#instance-method-getCustomHeadersFromRequest",
    "src/services/http/http.js~HTTP#getCustomHeadersFromRequest",
    "method"
  ],
  [
    "src/services/http/http.js~http#getipfromrequest",
    "class/src/services/http/http.js~HTTP.html#instance-method-getIPFromRequest",
    "src/services/http/http.js~HTTP#getIPFromRequest",
    "method"
  ],
  [
    "src/services/http/http.js~http#logrequests",
    "class/src/services/http/http.js~HTTP.html#instance-get-logRequests",
    "src/services/http/http.js~HTTP#logRequests",
    "member"
  ],
  [
    "src/services/http/http.js~http#normalizeheaders",
    "class/src/services/http/http.js~HTTP.html#instance-method-normalizeHeaders",
    "src/services/http/http.js~HTTP#normalizeHeaders",
    "method"
  ],
  [
    "src/services/http/http.js~httpfetchoptions",
    "typedef/index.html#static-typedef-HTTPFetchOptions",
    "src/services/http/http.js~HTTPFetchOptions",
    "typedef"
  ],
  [
    "src/services/http/http.js~headers",
    "https://developer.mozilla.org/en-US/docs/Web/API/Headers",
    "src/services/http/http.js~Headers",
    "external"
  ],
  [
    "src/services/http/index.js",
    "file/src/services/http/index.js.html",
    "src/services/http/index.js",
    "file"
  ],
  [
    "src/services/http/responsesbuilder.js",
    "file/src/services/http/responsesBuilder.js.html",
    "src/services/http/responsesBuilder.js",
    "file"
  ],
  [
    "src/services/http/responsesbuilder.js~responsesbuilder#constructor",
    "class/src/services/http/responsesBuilder.js~ResponsesBuilder.html#instance-constructor-constructor",
    "src/services/http/responsesBuilder.js~ResponsesBuilder#constructor",
    "method"
  ],
  [
    "src/services/http/responsesbuilder.js~responsesbuilder#htmlpostmessage",
    "class/src/services/http/responsesBuilder.js~ResponsesBuilder.html#instance-method-htmlPostMessage",
    "src/services/http/responsesBuilder.js~ResponsesBuilder#htmlPostMessage",
    "method"
  ],
  [
    "src/services/http/responsesbuilder.js~responsesbuilder#json",
    "class/src/services/http/responsesBuilder.js~ResponsesBuilder.html#instance-method-json",
    "src/services/http/responsesBuilder.js~ResponsesBuilder#json",
    "method"
  ],
  [
    "src/services/http/responsesbuilder.js~responsesbuilderpostmessageoptions",
    "typedef/index.html#static-typedef-ResponsesBuilderPostMessageOptions",
    "src/services/http/responsesBuilder.js~ResponsesBuilderPostMessageOptions",
    "typedef"
  ],
  [
    "src/services/index.js",
    "file/src/services/index.js.html",
    "src/services/index.js",
    "file"
  ],
  [
    "src/services/utils/ensurebearertoken.js",
    "file/src/services/utils/ensureBearerToken.js.html",
    "src/services/utils/ensureBearerToken.js",
    "file"
  ],
  [
    "src/services/utils/ensurebearertoken.js~ensurebearertoken#constructor",
    "class/src/services/utils/ensureBearerToken.js~EnsureBearerToken.html#instance-constructor-constructor",
    "src/services/utils/ensureBearerToken.js~EnsureBearerToken#constructor",
    "method"
  ],
  [
    "src/services/utils/ensurebearertoken.js~ensurebearertoken#middleware",
    "class/src/services/utils/ensureBearerToken.js~EnsureBearerToken.html#instance-method-middleware",
    "src/services/utils/ensureBearerToken.js~EnsureBearerToken#middleware",
    "method"
  ],
  [
    "src/services/utils/ensurebearertoken.js~ensurebearertoken#options",
    "class/src/services/utils/ensureBearerToken.js~EnsureBearerToken.html#instance-get-options",
    "src/services/utils/ensureBearerToken.js~EnsureBearerToken#options",
    "member"
  ],
  [
    "src/services/utils/ensurebearertoken.js~ensurebearertokenerroroptions",
    "typedef/index.html#static-typedef-EnsureBearerTokenErrorOptions",
    "src/services/utils/ensureBearerToken.js~EnsureBearerTokenErrorOptions",
    "typedef"
  ],
  [
    "src/services/utils/ensurebearertoken.js~ensurebearertokenoptions",
    "typedef/index.html#static-typedef-EnsureBearerTokenOptions",
    "src/services/utils/ensureBearerToken.js~EnsureBearerTokenOptions",
    "typedef"
  ],
  [
    "src/services/utils/index.js",
    "file/src/services/utils/index.js.html",
    "src/services/utils/index.js",
    "file"
  ],
  [
    "src/typedef.js",
    "file/src/typedef.js.html",
    "src/typedef.js",
    "file"
  ],
  [
    "src/typedef.js~apiclientbase",
    "https://homer0.github.io/wootils/class/wootils/shared/apiClient.js~APIClient.html",
    "src/typedef.js~APIClientBase",
    "external"
  ],
  [
    "src/typedef.js~apiclientendpoints",
    "https://homer0.github.io/wootils/typedef/index.html#static-typedef-APIClientEndpoints",
    "src/typedef.js~APIClientEndpoints",
    "external"
  ],
  [
    "src/typedef.js~appconfiguration",
    "https://homer0.github.io/wootils/class/wootils/node/appConfiguration.js~AppConfiguration.html",
    "src/typedef.js~AppConfiguration",
    "external"
  ],
  [
    "src/typedef.js~environmentutils",
    "https://homer0.github.io/wootils/class/wootils/node/environmentUtils.js~EnvironmentUtils.html",
    "src/typedef.js~EnvironmentUtils",
    "external"
  ],
  [
    "src/typedef.js~errorhandler",
    "https://homer0.github.io/wootils/class/wootils/node/errorHandler.js~ErrorHandler.html",
    "src/typedef.js~ErrorHandler",
    "external"
  ],
  [
    "src/typedef.js~express",
    "https://expressjs.com/en/4x/api.html",
    "src/typedef.js~Express",
    "external"
  ],
  [
    "src/typedef.js~expressmiddleware",
    "http://expressjs.com/en/guide/using-middleware.html",
    "src/typedef.js~ExpressMiddleware",
    "external"
  ],
  [
    "src/typedef.js~expressrequest",
    "https://expressjs.com/en/4x/api.html#req",
    "src/typedef.js~ExpressRequest",
    "external"
  ],
  [
    "src/typedef.js~expressresponse",
    "https://expressjs.com/en/4x/api.html#res",
    "src/typedef.js~ExpressResponse",
    "external"
  ],
  [
    "src/typedef.js~expressrouter",
    "https://expressjs.com/en/4x/api.html#router",
    "src/typedef.js~ExpressRouter",
    "external"
  ],
  [
    "src/typedef.js~logger",
    "https://homer0.github.io/wootils/class/wootils/node/logger.js~Logger.html",
    "src/typedef.js~Logger",
    "external"
  ],
  [
    "src/typedef.js~pathutils",
    "https://homer0.github.io/wootils/class/wootils/node/pathUtils.js~PathUtils.html",
    "src/typedef.js~PathUtils",
    "external"
  ],
  [
    "src/typedef.js~rootrequire",
    "https://homer0.github.io/wootils/function/index.html#static-function-rootRequire",
    "src/typedef.js~RootRequire",
    "external"
  ],
  [
    "src/utils/functions.js",
    "file/src/utils/functions.js.html",
    "src/utils/functions.js",
    "file"
  ],
  [
    "src/utils/wrappers.js",
    "file/src/utils/wrappers.js.html",
    "src/utils/wrappers.js",
    "file"
  ],
  [
    "src/utils/wrappers.js~controller",
    "typedef/index.html#static-typedef-Controller",
    "src/utils/wrappers.js~Controller",
    "typedef"
  ],
  [
    "src/utils/wrappers.js~controllercreator",
    "typedef/index.html#static-typedef-ControllerCreator",
    "src/utils/wrappers.js~ControllerCreator",
    "typedef"
  ],
  [
    "src/utils/wrappers.js~controllercreatorcallback",
    "typedef/index.html#static-typedef-ControllerCreatorCallback",
    "src/utils/wrappers.js~ControllerCreatorCallback",
    "typedef"
  ],
  [
    "src/utils/wrappers.js~controllermountcallback",
    "typedef/index.html#static-typedef-ControllerMountCallback",
    "src/utils/wrappers.js~ControllerMountCallback",
    "typedef"
  ],
  [
    "src/utils/wrappers.js~middleware",
    "typedef/index.html#static-typedef-Middleware",
    "src/utils/wrappers.js~Middleware",
    "typedef"
  ],
  [
    "src/utils/wrappers.js~middlewarecreator",
    "typedef/index.html#static-typedef-MiddlewareCreator",
    "src/utils/wrappers.js~MiddlewareCreator",
    "typedef"
  ],
  [
    "src/utils/wrappers.js~middlewarecreatorcallback",
    "typedef/index.html#static-typedef-MiddlewareCreatorCallback",
    "src/utils/wrappers.js~MiddlewareCreatorCallback",
    "typedef"
  ],
  [
    "src/utils/wrappers.js~middlewareusecallback",
    "typedef/index.html#static-typedef-MiddlewareUseCallback",
    "src/utils/wrappers.js~MiddlewareUseCallback",
    "typedef"
  ],
  [
    "src/utils/wrappers.js~provider",
    "typedef/index.html#static-typedef-Provider",
    "src/utils/wrappers.js~Provider",
    "typedef"
  ],
  [
    "src/utils/wrappers.js~providercreator",
    "typedef/index.html#static-typedef-ProviderCreator",
    "src/utils/wrappers.js~ProviderCreator",
    "typedef"
  ],
  [
    "src/utils/wrappers.js~providercreatorcallback",
    "typedef/index.html#static-typedef-ProviderCreatorCallback",
    "src/utils/wrappers.js~ProviderCreatorCallback",
    "typedef"
  ],
  [
    "src/utils/wrappers.js~providerregistrationcallback",
    "typedef/index.html#static-typedef-ProviderRegistrationCallback",
    "src/utils/wrappers.js~ProviderRegistrationCallback",
    "typedef"
  ]
]