window.esdocSearchIndex = [
  [
    "jimpex/src/services/api/client.js~apiclient",
    "class/src/services/api/client.js~APIClient.html",
    "<span>APIClient</span> <span class=\"search-result-import-path\">jimpex/src/services/api/client.js</span>",
    "class"
  ],
  [
    "jimpex/src/services/common/error.js~apperror",
    "class/src/services/common/error.js~AppError.html",
    "<span>AppError</span> <span class=\"search-result-import-path\">jimpex/src/services/common/error.js</span>",
    "class"
  ],
  [
    "jimpex/src/controllers/common/configuration.js~configurationcontroller",
    "class/src/controllers/common/configuration.js~ConfigurationController.html",
    "<span>ConfigurationController</span> <span class=\"search-result-import-path\">jimpex/src/controllers/common/configuration.js</span>",
    "class"
  ],
  [
    "jimpex/src/services/api/ensurebearerauthentication.js~ensurebearerauthentication",
    "class/src/services/api/ensureBearerAuthentication.js~EnsureBearerAuthentication.html",
    "<span>EnsureBearerAuthentication</span> <span class=\"search-result-import-path\">jimpex/src/services/api/ensureBearerAuthentication.js</span>",
    "class"
  ],
  [
    "jimpex/src/middlewares/common/errorhandler.js~errorhandler",
    "class/src/middlewares/common/errorHandler.js~ErrorHandler.html",
    "<span>ErrorHandler</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/common/errorHandler.js</span>",
    "class"
  ],
  [
    "jimpex/src/middlewares/html/fasthtml.js~fasthtml",
    "class/src/middlewares/html/fastHTML.js~FastHTML.html",
    "<span>FastHTML</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/html/fastHTML.js</span>",
    "class"
  ],
  [
    "jimpex/src/middlewares/common/forcehttps.js~forcehttps",
    "class/src/middlewares/common/forceHTTPS.js~ForceHTTPS.html",
    "<span>ForceHTTPS</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/common/forceHTTPS.js</span>",
    "class"
  ],
  [
    "jimpex/src/services/frontend/frontendfs.js~frontendfs",
    "class/src/services/frontend/frontendFs.js~FrontendFs.html",
    "<span>FrontendFs</span> <span class=\"search-result-import-path\">jimpex/src/services/frontend/frontendFs.js</span>",
    "class"
  ],
  [
    "jimpex/src/services/html/htmlgenerator.js~htmlgenerator",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html",
    "<span>HTMLGenerator</span> <span class=\"search-result-import-path\">jimpex/src/services/html/htmlGenerator.js</span>",
    "class"
  ],
  [
    "jimpex/src/services/http/http.js~http",
    "class/src/services/http/http.js~HTTP.html",
    "<span>HTTP</span> <span class=\"search-result-import-path\">jimpex/src/services/http/http.js</span>",
    "class"
  ],
  [
    "jimpex/src/controllers/common/health.js~healthcontroller",
    "class/src/controllers/common/health.js~HealthController.html",
    "<span>HealthController</span> <span class=\"search-result-import-path\">jimpex/src/controllers/common/health.js</span>",
    "class"
  ],
  [
    "jimpex/src/app/index.js~jimpex",
    "class/src/app/index.js~Jimpex.html",
    "<span>Jimpex</span> <span class=\"search-result-import-path\">jimpex/src/app/index.js</span>",
    "class"
  ],
  [
    "jimpex/src/services/http/responsesbuilder.js~responsesbuilder",
    "class/src/services/http/responsesBuilder.js~ResponsesBuilder.html",
    "<span>ResponsesBuilder</span> <span class=\"search-result-import-path\">jimpex/src/services/http/responsesBuilder.js</span>",
    "class"
  ],
  [
    "jimpex/src/controllers/common/rootstatics.js~rootstaticscontroller",
    "class/src/controllers/common/rootStatics.js~RootStaticsController.html",
    "<span>RootStaticsController</span> <span class=\"search-result-import-path\">jimpex/src/controllers/common/rootStatics.js</span>",
    "class"
  ],
  [
    "jimpex/src/middlewares/html/showhtml.js~showhtml",
    "class/src/middlewares/html/showHTML.js~ShowHTML.html",
    "<span>ShowHTML</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/html/showHTML.js</span>",
    "class"
  ],
  [
    "jimpex/src/services/api/versionvalidator.js~versionvalidator",
    "class/src/services/api/versionValidator.js~VersionValidator.html",
    "<span>VersionValidator</span> <span class=\"search-result-import-path\">jimpex/src/services/api/versionValidator.js</span>",
    "class"
  ],
  [
    "jimpex/src/controllers/api/versionvalidator.js~versionvalidatorcontroller",
    "class/src/controllers/api/versionValidator.js~VersionValidatorController.html",
    "<span>VersionValidatorController</span> <span class=\"search-result-import-path\">jimpex/src/controllers/api/versionValidator.js</span>",
    "class"
  ],
  [
    "jimpex/src/services/api/index.js~all",
    "variable/index.html#static-variable-all",
    "<span>all</span> <span class=\"search-result-import-path\">jimpex/src/services/api/index.js</span>",
    "variable"
  ],
  [
    "jimpex/src/services/common/index.js~all",
    "variable/index.html#static-variable-all",
    "<span>all</span> <span class=\"search-result-import-path\">jimpex/src/services/common/index.js</span>",
    "variable"
  ],
  [
    "jimpex/src/services/http/index.js~all",
    "variable/index.html#static-variable-all",
    "<span>all</span> <span class=\"search-result-import-path\">jimpex/src/services/http/index.js</span>",
    "variable"
  ],
  [
    "jimpex/src/services/api/client.js~apiclient",
    "variable/index.html#static-variable-apiClient",
    "<span>apiClient</span> <span class=\"search-result-import-path\">jimpex/src/services/api/client.js</span>",
    "variable"
  ],
  [
    "jimpex/src/services/api/client.js~apiclientcustom",
    "function/index.html#static-function-apiClientCustom",
    "<span>apiClientCustom</span> <span class=\"search-result-import-path\">jimpex/src/services/api/client.js</span>",
    "function"
  ],
  [
    "jimpex/src/services/common/error.js~apperror",
    "variable/index.html#static-variable-appError",
    "<span>appError</span> <span class=\"search-result-import-path\">jimpex/src/services/common/error.js</span>",
    "variable"
  ],
  [
    "jimpex/src/controllers/common/configuration.js~configurationcontroller",
    "variable/index.html#static-variable-configurationController",
    "<span>configurationController</span> <span class=\"search-result-import-path\">jimpex/src/controllers/common/configuration.js</span>",
    "variable"
  ],
  [
    "jimpex/src/utils/wrappers.js~controller",
    "function/index.html#static-function-controller",
    "<span>controller</span> <span class=\"search-result-import-path\">jimpex/src/utils/wrappers.js</span>",
    "function"
  ],
  [
    "jimpex/src/services/api/ensurebearerauthentication.js~ensurebearerauthentication",
    "variable/index.html#static-variable-ensureBearerAuthentication",
    "<span>ensureBearerAuthentication</span> <span class=\"search-result-import-path\">jimpex/src/services/api/ensureBearerAuthentication.js</span>",
    "variable"
  ],
  [
    "jimpex/src/middlewares/common/errorhandler.js~errorhandler",
    "variable/index.html#static-variable-errorHandler",
    "<span>errorHandler</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/common/errorHandler.js</span>",
    "variable"
  ],
  [
    "jimpex/src/middlewares/html/fasthtml.js~fasthtml",
    "variable/index.html#static-variable-fastHTML",
    "<span>fastHTML</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/html/fastHTML.js</span>",
    "variable"
  ],
  [
    "jimpex/src/middlewares/html/fasthtml.js~fasthtmlcustom",
    "function/index.html#static-function-fastHTMLCustom",
    "<span>fastHTMLCustom</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/html/fastHTML.js</span>",
    "function"
  ],
  [
    "jimpex/src/middlewares/common/forcehttps.js~forcehttps",
    "variable/index.html#static-variable-forceHTTPS",
    "<span>forceHTTPS</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/common/forceHTTPS.js</span>",
    "variable"
  ],
  [
    "jimpex/src/middlewares/common/forcehttps.js~forcehttpscustom",
    "function/index.html#static-function-forceHTTPSCustom",
    "<span>forceHTTPSCustom</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/common/forceHTTPS.js</span>",
    "function"
  ],
  [
    "jimpex/src/services/frontend/frontendfs.js~frontendfs",
    "variable/index.html#static-variable-frontendFs",
    "<span>frontendFs</span> <span class=\"search-result-import-path\">jimpex/src/services/frontend/frontendFs.js</span>",
    "variable"
  ],
  [
    "jimpex/src/controllers/common/health.js~healthcontroller",
    "variable/index.html#static-variable-healthController",
    "<span>healthController</span> <span class=\"search-result-import-path\">jimpex/src/controllers/common/health.js</span>",
    "variable"
  ],
  [
    "jimpex/src/services/html/htmlgenerator.js~htmlgenerator",
    "variable/index.html#static-variable-htmlGenerator",
    "<span>htmlGenerator</span> <span class=\"search-result-import-path\">jimpex/src/services/html/htmlGenerator.js</span>",
    "variable"
  ],
  [
    "jimpex/src/services/html/htmlgenerator.js~htmlgeneratorcustom",
    "function/index.html#static-function-htmlGeneratorCustom",
    "<span>htmlGeneratorCustom</span> <span class=\"search-result-import-path\">jimpex/src/services/html/htmlGenerator.js</span>",
    "function"
  ],
  [
    "jimpex/src/services/http/http.js~http",
    "variable/index.html#static-variable-http",
    "<span>http</span> <span class=\"search-result-import-path\">jimpex/src/services/http/http.js</span>",
    "variable"
  ],
  [
    "jimpex/src/utils/wrappers.js~middleware",
    "function/index.html#static-function-middleware",
    "<span>middleware</span> <span class=\"search-result-import-path\">jimpex/src/utils/wrappers.js</span>",
    "function"
  ],
  [
    "jimpex/src/services/http/responsesbuilder.js~responsesbuilder",
    "variable/index.html#static-variable-responsesBuilder",
    "<span>responsesBuilder</span> <span class=\"search-result-import-path\">jimpex/src/services/http/responsesBuilder.js</span>",
    "variable"
  ],
  [
    "jimpex/src/controllers/common/rootstatics.js~rootstaticscontroller",
    "variable/index.html#static-variable-rootStaticsController",
    "<span>rootStaticsController</span> <span class=\"search-result-import-path\">jimpex/src/controllers/common/rootStatics.js</span>",
    "variable"
  ],
  [
    "jimpex/src/controllers/common/rootstatics.js~rootstaticscontrollercustom",
    "function/index.html#static-function-rootStaticsControllerCustom",
    "<span>rootStaticsControllerCustom</span> <span class=\"search-result-import-path\">jimpex/src/controllers/common/rootStatics.js</span>",
    "function"
  ],
  [
    "jimpex/src/services/common/sendfile.js~sendfile",
    "function/index.html#static-function-sendFile",
    "<span>sendFile</span> <span class=\"search-result-import-path\">jimpex/src/services/common/sendFile.js</span>",
    "function"
  ],
  [
    "jimpex/src/services/common/sendfile.js~sendfileprovider",
    "variable/index.html#static-variable-sendFileProvider",
    "<span>sendFileProvider</span> <span class=\"search-result-import-path\">jimpex/src/services/common/sendFile.js</span>",
    "variable"
  ],
  [
    "jimpex/src/middlewares/html/showhtml.js~showhtml",
    "variable/index.html#static-variable-showHTML",
    "<span>showHTML</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/html/showHTML.js</span>",
    "variable"
  ],
  [
    "jimpex/src/middlewares/html/showhtml.js~showhtmlcustom",
    "function/index.html#static-function-showHTMLCustom",
    "<span>showHTMLCustom</span> <span class=\"search-result-import-path\">jimpex/src/middlewares/html/showHTML.js</span>",
    "function"
  ],
  [
    "jimpex/src/services/api/versionvalidator.js~versionvalidator",
    "variable/index.html#static-variable-versionValidator",
    "<span>versionValidator</span> <span class=\"search-result-import-path\">jimpex/src/services/api/versionValidator.js</span>",
    "variable"
  ],
  [
    "jimpex/src/controllers/api/versionvalidator.js~versionvalidatorcontroller",
    "variable/index.html#static-variable-versionValidatorController",
    "<span>versionValidatorController</span> <span class=\"search-result-import-path\">jimpex/src/controllers/api/versionValidator.js</span>",
    "variable"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/app/index.js",
    "file/src/app/index.js.html",
    "src/app/index.js",
    "file"
  ],
  [
    "src/app/index.js~jimpex#boot",
    "class/src/app/index.js~Jimpex.html#instance-method-boot",
    "src/app/index.js~Jimpex#boot",
    "method"
  ],
  [
    "src/app/index.js~jimpex#constructor",
    "class/src/app/index.js~Jimpex.html#instance-constructor-constructor",
    "src/app/index.js~Jimpex#constructor",
    "method"
  ],
  [
    "src/app/index.js~jimpex#disabletlsvalidation",
    "class/src/app/index.js~Jimpex.html#instance-method-disableTLSValidation",
    "src/app/index.js~Jimpex#disableTLSValidation",
    "method"
  ],
  [
    "src/app/index.js~jimpex#emitevent",
    "class/src/app/index.js~Jimpex.html#instance-method-emitEvent",
    "src/app/index.js~Jimpex#emitEvent",
    "method"
  ],
  [
    "src/app/index.js~jimpex#express",
    "class/src/app/index.js~Jimpex.html#instance-member-express",
    "src/app/index.js~Jimpex#express",
    "member"
  ],
  [
    "src/app/index.js~jimpex#instance",
    "class/src/app/index.js~Jimpex.html#instance-member-instance",
    "src/app/index.js~Jimpex#instance",
    "member"
  ],
  [
    "src/app/index.js~jimpex#mount",
    "class/src/app/index.js~Jimpex.html#instance-method-mount",
    "src/app/index.js~Jimpex#mount",
    "method"
  ],
  [
    "src/app/index.js~jimpex#mountqueue",
    "class/src/app/index.js~Jimpex.html#instance-member-mountQueue",
    "src/app/index.js~Jimpex#mountQueue",
    "member"
  ],
  [
    "src/app/index.js~jimpex#options",
    "class/src/app/index.js~Jimpex.html#instance-member-options",
    "src/app/index.js~Jimpex#options",
    "member"
  ],
  [
    "src/app/index.js~jimpex#start",
    "class/src/app/index.js~Jimpex.html#instance-method-start",
    "src/app/index.js~Jimpex#start",
    "method"
  ],
  [
    "src/app/index.js~jimpex#stop",
    "class/src/app/index.js~Jimpex.html#instance-method-stop",
    "src/app/index.js~Jimpex#stop",
    "method"
  ],
  [
    "src/app/index.js~jimpex#use",
    "class/src/app/index.js~Jimpex.html#instance-method-use",
    "src/app/index.js~Jimpex#use",
    "method"
  ],
  [
    "src/app/typedef.js",
    "file/src/app/typedef.js.html",
    "src/app/typedef.js",
    "file"
  ],
  [
    "src/app/typedef.js~jimpexconfigurationoptions",
    "typedef/index.html#static-typedef-JimpexConfigurationOptions",
    "src/app/typedef.js~JimpexConfigurationOptions",
    "typedef"
  ],
  [
    "src/app/typedef.js~jimpexdefaultservicesoptions",
    "typedef/index.html#static-typedef-JimpexDefaultServicesOptions",
    "src/app/typedef.js~JimpexDefaultServicesOptions",
    "typedef"
  ],
  [
    "src/app/typedef.js~jimpexexpressoptions",
    "typedef/index.html#static-typedef-JimpexExpressOptions",
    "src/app/typedef.js~JimpexExpressOptions",
    "typedef"
  ],
  [
    "src/app/typedef.js~jimpexoptions",
    "typedef/index.html#static-typedef-JimpexOptions",
    "src/app/typedef.js~JimpexOptions",
    "typedef"
  ],
  [
    "src/app/typedef.js~jimpexstaticsoptions",
    "typedef/index.html#static-typedef-JimpexStaticsOptions",
    "src/app/typedef.js~JimpexStaticsOptions",
    "typedef"
  ],
  [
    "src/app/typedef.js~jimple",
    "https://yarnpkg.com/en/package/jimple",
    "src/app/typedef.js~Jimple",
    "external"
  ],
  [
    "src/controllers/api/index.js",
    "file/src/controllers/api/index.js.html",
    "src/controllers/api/index.js",
    "file"
  ],
  [
    "src/controllers/api/versionvalidator.js",
    "file/src/controllers/api/versionValidator.js.html",
    "src/controllers/api/versionValidator.js",
    "file"
  ],
  [
    "src/controllers/api/versionvalidator.js~versionvalidatorcontroller#constructor",
    "class/src/controllers/api/versionValidator.js~VersionValidatorController.html#instance-constructor-constructor",
    "src/controllers/api/versionValidator.js~VersionValidatorController#constructor",
    "method"
  ],
  [
    "src/controllers/api/versionvalidator.js~versionvalidatorcontroller#validate",
    "class/src/controllers/api/versionValidator.js~VersionValidatorController.html#instance-method-validate",
    "src/controllers/api/versionValidator.js~VersionValidatorController#validate",
    "method"
  ],
  [
    "src/controllers/api/versionvalidator.js~versionvalidatorcontroller#versionvalidator",
    "class/src/controllers/api/versionValidator.js~VersionValidatorController.html#instance-member-versionValidator",
    "src/controllers/api/versionValidator.js~VersionValidatorController#versionValidator",
    "member"
  ],
  [
    "src/controllers/common/configuration.js",
    "file/src/controllers/common/configuration.js.html",
    "src/controllers/common/configuration.js",
    "file"
  ],
  [
    "src/controllers/common/configuration.js~configurationcontroller#appconfiguration",
    "class/src/controllers/common/configuration.js~ConfigurationController.html#instance-member-appConfiguration",
    "src/controllers/common/configuration.js~ConfigurationController#appConfiguration",
    "member"
  ],
  [
    "src/controllers/common/configuration.js~configurationcontroller#constructor",
    "class/src/controllers/common/configuration.js~ConfigurationController.html#instance-constructor-constructor",
    "src/controllers/common/configuration.js~ConfigurationController#constructor",
    "method"
  ],
  [
    "src/controllers/common/configuration.js~configurationcontroller#getconfigurationresponse",
    "class/src/controllers/common/configuration.js~ConfigurationController.html#instance-method-getConfigurationResponse",
    "src/controllers/common/configuration.js~ConfigurationController#getConfigurationResponse",
    "method"
  ],
  [
    "src/controllers/common/configuration.js~configurationcontroller#responsesbuilder",
    "class/src/controllers/common/configuration.js~ConfigurationController.html#instance-member-responsesBuilder",
    "src/controllers/common/configuration.js~ConfigurationController#responsesBuilder",
    "member"
  ],
  [
    "src/controllers/common/configuration.js~configurationcontroller#showconfiguration",
    "class/src/controllers/common/configuration.js~ConfigurationController.html#instance-method-showConfiguration",
    "src/controllers/common/configuration.js~ConfigurationController#showConfiguration",
    "method"
  ],
  [
    "src/controllers/common/configuration.js~configurationcontroller#switchconfiguration",
    "class/src/controllers/common/configuration.js~ConfigurationController.html#instance-method-switchConfiguration",
    "src/controllers/common/configuration.js~ConfigurationController#switchConfiguration",
    "method"
  ],
  [
    "src/controllers/common/health.js",
    "file/src/controllers/common/health.js.html",
    "src/controllers/common/health.js",
    "file"
  ],
  [
    "src/controllers/common/health.js~healthcontroller#appconfiguration",
    "class/src/controllers/common/health.js~HealthController.html#instance-member-appConfiguration",
    "src/controllers/common/health.js~HealthController#appConfiguration",
    "member"
  ],
  [
    "src/controllers/common/health.js~healthcontroller#constructor",
    "class/src/controllers/common/health.js~HealthController.html#instance-constructor-constructor",
    "src/controllers/common/health.js~HealthController#constructor",
    "method"
  ],
  [
    "src/controllers/common/health.js~healthcontroller#health",
    "class/src/controllers/common/health.js~HealthController.html#instance-method-health",
    "src/controllers/common/health.js~HealthController#health",
    "method"
  ],
  [
    "src/controllers/common/health.js~healthcontroller#responsesbuilder",
    "class/src/controllers/common/health.js~HealthController.html#instance-member-responsesBuilder",
    "src/controllers/common/health.js~HealthController#responsesBuilder",
    "member"
  ],
  [
    "src/controllers/common/index.js",
    "file/src/controllers/common/index.js.html",
    "src/controllers/common/index.js",
    "file"
  ],
  [
    "src/controllers/common/rootstatics.js",
    "file/src/controllers/common/rootStatics.js.html",
    "src/controllers/common/rootStatics.js",
    "file"
  ],
  [
    "src/controllers/common/rootstatics.js~rootstaticscontroller#_parsefiles",
    "class/src/controllers/common/rootStatics.js~RootStaticsController.html#instance-method-_parseFiles",
    "src/controllers/common/rootStatics.js~RootStaticsController#_parseFiles",
    "method"
  ],
  [
    "src/controllers/common/rootstatics.js~rootstaticscontroller#constructor",
    "class/src/controllers/common/rootStatics.js~RootStaticsController.html#instance-constructor-constructor",
    "src/controllers/common/rootStatics.js~RootStaticsController#constructor",
    "method"
  ],
  [
    "src/controllers/common/rootstatics.js~rootstaticscontroller#files",
    "class/src/controllers/common/rootStatics.js~RootStaticsController.html#instance-member-files",
    "src/controllers/common/rootStatics.js~RootStaticsController#files",
    "member"
  ],
  [
    "src/controllers/common/rootstatics.js~rootstaticscontroller#getfileentries",
    "class/src/controllers/common/rootStatics.js~RootStaticsController.html#instance-method-getFileEntries",
    "src/controllers/common/rootStatics.js~RootStaticsController#getFileEntries",
    "method"
  ],
  [
    "src/controllers/common/rootstatics.js~rootstaticscontroller#sendfile",
    "class/src/controllers/common/rootStatics.js~RootStaticsController.html#instance-member-sendFile",
    "src/controllers/common/rootStatics.js~RootStaticsController#sendFile",
    "member"
  ],
  [
    "src/controllers/common/rootstatics.js~rootstaticscontroller#servefile",
    "class/src/controllers/common/rootStatics.js~RootStaticsController.html#instance-method-serveFile",
    "src/controllers/common/rootStatics.js~RootStaticsController#serveFile",
    "method"
  ],
  [
    "src/controllers/index.js",
    "file/src/controllers/index.js.html",
    "src/controllers/index.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/middlewares/common/errorhandler.js",
    "file/src/middlewares/common/errorHandler.js.html",
    "src/middlewares/common/errorHandler.js",
    "file"
  ],
  [
    "src/middlewares/common/errorhandler.js~errorhandler#apperror",
    "class/src/middlewares/common/errorHandler.js~ErrorHandler.html#instance-member-AppError",
    "src/middlewares/common/errorHandler.js~ErrorHandler#AppError",
    "member"
  ],
  [
    "src/middlewares/common/errorhandler.js~errorhandler#applogger",
    "class/src/middlewares/common/errorHandler.js~ErrorHandler.html#instance-member-appLogger",
    "src/middlewares/common/errorHandler.js~ErrorHandler#appLogger",
    "member"
  ],
  [
    "src/middlewares/common/errorhandler.js~errorhandler#constructor",
    "class/src/middlewares/common/errorHandler.js~ErrorHandler.html#instance-constructor-constructor",
    "src/middlewares/common/errorHandler.js~ErrorHandler#constructor",
    "method"
  ],
  [
    "src/middlewares/common/errorhandler.js~errorhandler#middleware",
    "class/src/middlewares/common/errorHandler.js~ErrorHandler.html#instance-method-middleware",
    "src/middlewares/common/errorHandler.js~ErrorHandler#middleware",
    "method"
  ],
  [
    "src/middlewares/common/errorhandler.js~errorhandler#responsesbuilder",
    "class/src/middlewares/common/errorHandler.js~ErrorHandler.html#instance-member-responsesBuilder",
    "src/middlewares/common/errorHandler.js~ErrorHandler#responsesBuilder",
    "member"
  ],
  [
    "src/middlewares/common/errorhandler.js~errorhandler#showerrors",
    "class/src/middlewares/common/errorHandler.js~ErrorHandler.html#instance-member-showErrors",
    "src/middlewares/common/errorHandler.js~ErrorHandler#showErrors",
    "member"
  ],
  [
    "src/middlewares/common/forcehttps.js",
    "file/src/middlewares/common/forceHTTPS.js.html",
    "src/middlewares/common/forceHTTPS.js",
    "file"
  ],
  [
    "src/middlewares/common/forcehttps.js~forcehttps#constructor",
    "class/src/middlewares/common/forceHTTPS.js~ForceHTTPS.html#instance-constructor-constructor",
    "src/middlewares/common/forceHTTPS.js~ForceHTTPS#constructor",
    "method"
  ],
  [
    "src/middlewares/common/forcehttps.js~forcehttps#ignoredroutes",
    "class/src/middlewares/common/forceHTTPS.js~ForceHTTPS.html#instance-member-ignoredRoutes",
    "src/middlewares/common/forceHTTPS.js~ForceHTTPS#ignoredRoutes",
    "member"
  ],
  [
    "src/middlewares/common/forcehttps.js~forcehttps#middleware",
    "class/src/middlewares/common/forceHTTPS.js~ForceHTTPS.html#instance-method-middleware",
    "src/middlewares/common/forceHTTPS.js~ForceHTTPS#middleware",
    "method"
  ],
  [
    "src/middlewares/common/index.js",
    "file/src/middlewares/common/index.js.html",
    "src/middlewares/common/index.js",
    "file"
  ],
  [
    "src/middlewares/html/fasthtml.js",
    "file/src/middlewares/html/fastHTML.js.html",
    "src/middlewares/html/fastHTML.js",
    "file"
  ],
  [
    "src/middlewares/html/fasthtml.js~fasthtml#constructor",
    "class/src/middlewares/html/fastHTML.js~FastHTML.html#instance-constructor-constructor",
    "src/middlewares/html/fastHTML.js~FastHTML#constructor",
    "method"
  ],
  [
    "src/middlewares/html/fasthtml.js~fasthtml#file",
    "class/src/middlewares/html/fastHTML.js~FastHTML.html#instance-member-file",
    "src/middlewares/html/fastHTML.js~FastHTML#file",
    "member"
  ],
  [
    "src/middlewares/html/fasthtml.js~fasthtml#htmlgenerator",
    "class/src/middlewares/html/fastHTML.js~FastHTML.html#instance-member-htmlGenerator",
    "src/middlewares/html/fastHTML.js~FastHTML#htmlGenerator",
    "member"
  ],
  [
    "src/middlewares/html/fasthtml.js~fasthtml#ignoredroutes",
    "class/src/middlewares/html/fastHTML.js~FastHTML.html#instance-member-ignoredRoutes",
    "src/middlewares/html/fastHTML.js~FastHTML#ignoredRoutes",
    "member"
  ],
  [
    "src/middlewares/html/fasthtml.js~fasthtml#middleware",
    "class/src/middlewares/html/fastHTML.js~FastHTML.html#instance-method-middleware",
    "src/middlewares/html/fastHTML.js~FastHTML#middleware",
    "method"
  ],
  [
    "src/middlewares/html/fasthtml.js~fasthtml#sendfile",
    "class/src/middlewares/html/fastHTML.js~FastHTML.html#instance-member-sendFile",
    "src/middlewares/html/fastHTML.js~FastHTML#sendFile",
    "member"
  ],
  [
    "src/middlewares/html/index.js",
    "file/src/middlewares/html/index.js.html",
    "src/middlewares/html/index.js",
    "file"
  ],
  [
    "src/middlewares/html/showhtml.js",
    "file/src/middlewares/html/showHTML.js.html",
    "src/middlewares/html/showHTML.js",
    "file"
  ],
  [
    "src/middlewares/html/showhtml.js~showhtml#constructor",
    "class/src/middlewares/html/showHTML.js~ShowHTML.html#instance-constructor-constructor",
    "src/middlewares/html/showHTML.js~ShowHTML#constructor",
    "method"
  ],
  [
    "src/middlewares/html/showhtml.js~showhtml#file",
    "class/src/middlewares/html/showHTML.js~ShowHTML.html#instance-member-file",
    "src/middlewares/html/showHTML.js~ShowHTML#file",
    "member"
  ],
  [
    "src/middlewares/html/showhtml.js~showhtml#htmlgenerator",
    "class/src/middlewares/html/showHTML.js~ShowHTML.html#instance-member-htmlGenerator",
    "src/middlewares/html/showHTML.js~ShowHTML#htmlGenerator",
    "member"
  ],
  [
    "src/middlewares/html/showhtml.js~showhtml#middleware",
    "class/src/middlewares/html/showHTML.js~ShowHTML.html#instance-method-middleware",
    "src/middlewares/html/showHTML.js~ShowHTML#middleware",
    "method"
  ],
  [
    "src/middlewares/html/showhtml.js~showhtml#sendfile",
    "class/src/middlewares/html/showHTML.js~ShowHTML.html#instance-member-sendFile",
    "src/middlewares/html/showHTML.js~ShowHTML#sendFile",
    "member"
  ],
  [
    "src/middlewares/index.js",
    "file/src/middlewares/index.js.html",
    "src/middlewares/index.js",
    "file"
  ],
  [
    "src/services/api/client.js",
    "file/src/services/api/client.js.html",
    "src/services/api/client.js",
    "file"
  ],
  [
    "src/services/api/client.js~apiclient#apperror",
    "class/src/services/api/client.js~APIClient.html#instance-member-AppError",
    "src/services/api/client.js~APIClient#AppError",
    "member"
  ],
  [
    "src/services/api/client.js~apiclient#apiconfig",
    "class/src/services/api/client.js~APIClient.html#instance-member-apiConfig",
    "src/services/api/client.js~APIClient#apiConfig",
    "member"
  ],
  [
    "src/services/api/client.js~apiclient#constructor",
    "class/src/services/api/client.js~APIClient.html#instance-constructor-constructor",
    "src/services/api/client.js~APIClient#constructor",
    "method"
  ],
  [
    "src/services/api/client.js~apiclient#error",
    "class/src/services/api/client.js~APIClient.html#instance-method-error",
    "src/services/api/client.js~APIClient#error",
    "method"
  ],
  [
    "src/services/api/ensurebearerauthentication.js",
    "file/src/services/api/ensureBearerAuthentication.js.html",
    "src/services/api/ensureBearerAuthentication.js",
    "file"
  ],
  [
    "src/services/api/ensurebearerauthentication.js~ensurebearerauthentication#apperror",
    "class/src/services/api/ensureBearerAuthentication.js~EnsureBearerAuthentication.html#instance-member-AppError",
    "src/services/api/ensureBearerAuthentication.js~EnsureBearerAuthentication#AppError",
    "member"
  ],
  [
    "src/services/api/ensurebearerauthentication.js~ensurebearerauthentication#bearerregex",
    "class/src/services/api/ensureBearerAuthentication.js~EnsureBearerAuthentication.html#instance-member-bearerRegex",
    "src/services/api/ensureBearerAuthentication.js~EnsureBearerAuthentication#bearerRegex",
    "member"
  ],
  [
    "src/services/api/ensurebearerauthentication.js~ensurebearerauthentication#constructor",
    "class/src/services/api/ensureBearerAuthentication.js~EnsureBearerAuthentication.html#instance-constructor-constructor",
    "src/services/api/ensureBearerAuthentication.js~EnsureBearerAuthentication#constructor",
    "method"
  ],
  [
    "src/services/api/ensurebearerauthentication.js~ensurebearerauthentication#middleware",
    "class/src/services/api/ensureBearerAuthentication.js~EnsureBearerAuthentication.html#instance-method-middleware",
    "src/services/api/ensureBearerAuthentication.js~EnsureBearerAuthentication#middleware",
    "method"
  ],
  [
    "src/services/api/index.js",
    "file/src/services/api/index.js.html",
    "src/services/api/index.js",
    "file"
  ],
  [
    "src/services/api/versionvalidator.js",
    "file/src/services/api/versionValidator.js.html",
    "src/services/api/versionValidator.js",
    "file"
  ],
  [
    "src/services/api/versionvalidator.js~versionvalidator#apperror",
    "class/src/services/api/versionValidator.js~VersionValidator.html#instance-member-AppError",
    "src/services/api/versionValidator.js~VersionValidator#AppError",
    "member"
  ],
  [
    "src/services/api/versionvalidator.js~versionvalidator#appconfiguration",
    "class/src/services/api/versionValidator.js~VersionValidator.html#instance-member-appConfiguration",
    "src/services/api/versionValidator.js~VersionValidator#appConfiguration",
    "member"
  ],
  [
    "src/services/api/versionvalidator.js~versionvalidator#constructor",
    "class/src/services/api/versionValidator.js~VersionValidator.html#instance-constructor-constructor",
    "src/services/api/versionValidator.js~VersionValidator#constructor",
    "method"
  ],
  [
    "src/services/api/versionvalidator.js~versionvalidator#middleware",
    "class/src/services/api/versionValidator.js~VersionValidator.html#instance-method-middleware",
    "src/services/api/versionValidator.js~VersionValidator#middleware",
    "method"
  ],
  [
    "src/services/api/versionvalidator.js~versionvalidator#responsesbuilder",
    "class/src/services/api/versionValidator.js~VersionValidator.html#instance-member-responsesBuilder",
    "src/services/api/versionValidator.js~VersionValidator#responsesBuilder",
    "member"
  ],
  [
    "src/services/common/error.js",
    "file/src/services/common/error.js.html",
    "src/services/common/error.js",
    "file"
  ],
  [
    "src/services/common/error.js~apperror#constructor",
    "class/src/services/common/error.js~AppError.html#instance-constructor-constructor",
    "src/services/common/error.js~AppError#constructor",
    "method"
  ],
  [
    "src/services/common/error.js~apperror#extras",
    "class/src/services/common/error.js~AppError.html#instance-member-extras",
    "src/services/common/error.js~AppError#extras",
    "member"
  ],
  [
    "src/services/common/index.js",
    "file/src/services/common/index.js.html",
    "src/services/common/index.js",
    "file"
  ],
  [
    "src/services/common/sendfile.js",
    "file/src/services/common/sendFile.js.html",
    "src/services/common/sendFile.js",
    "file"
  ],
  [
    "src/services/common/sendfile.js~sendfile",
    "typedef/index.html#static-typedef-SendFile",
    "src/services/common/sendFile.js~SendFile",
    "typedef"
  ],
  [
    "src/services/frontend/frontendfs.js",
    "file/src/services/frontend/frontendFs.js.html",
    "src/services/frontend/frontendFs.js",
    "file"
  ],
  [
    "src/services/frontend/frontendfs.js~frontendfs#constructor",
    "class/src/services/frontend/frontendFs.js~FrontendFs.html#instance-constructor-constructor",
    "src/services/frontend/frontendFs.js~FrontendFs#constructor",
    "method"
  ],
  [
    "src/services/frontend/frontendfs.js~frontendfs#delete",
    "class/src/services/frontend/frontendFs.js~FrontendFs.html#instance-method-delete",
    "src/services/frontend/frontendFs.js~FrontendFs#delete",
    "method"
  ],
  [
    "src/services/frontend/frontendfs.js~frontendfs#pathutils",
    "class/src/services/frontend/frontendFs.js~FrontendFs.html#instance-member-pathUtils",
    "src/services/frontend/frontendFs.js~FrontendFs#pathUtils",
    "member"
  ],
  [
    "src/services/frontend/frontendfs.js~frontendfs#read",
    "class/src/services/frontend/frontendFs.js~FrontendFs.html#instance-method-read",
    "src/services/frontend/frontendFs.js~FrontendFs#read",
    "method"
  ],
  [
    "src/services/frontend/frontendfs.js~frontendfs#write",
    "class/src/services/frontend/frontendFs.js~FrontendFs.html#instance-method-write",
    "src/services/frontend/frontendFs.js~FrontendFs#write",
    "method"
  ],
  [
    "src/services/frontend/index.js",
    "file/src/services/frontend/index.js.html",
    "src/services/frontend/index.js",
    "file"
  ],
  [
    "src/services/html/htmlgenerator.js",
    "file/src/services/html/htmlGenerator.js.html",
    "src/services/html/htmlGenerator.js",
    "file"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgenerator#appconfiguration",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html#instance-member-appConfiguration",
    "src/services/html/htmlGenerator.js~HTMLGenerator#appConfiguration",
    "member"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgenerator#applogger",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html#instance-member-appLogger",
    "src/services/html/htmlGenerator.js~HTMLGenerator#appLogger",
    "member"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgenerator#constructor",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html#instance-constructor-constructor",
    "src/services/html/htmlGenerator.js~HTMLGenerator#constructor",
    "method"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgenerator#frontendfs",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html#instance-member-frontendFs",
    "src/services/html/htmlGenerator.js~HTMLGenerator#frontendFs",
    "member"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgenerator#generatehtml",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html#instance-method-generateHTML",
    "src/services/html/htmlGenerator.js~HTMLGenerator#generateHTML",
    "method"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgenerator#getfile",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html#instance-method-getFile",
    "src/services/html/htmlGenerator.js~HTMLGenerator#getFile",
    "method"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgenerator#getvalues",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html#instance-method-getValues",
    "src/services/html/htmlGenerator.js~HTMLGenerator#getValues",
    "method"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgenerator#options",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html#instance-member-options",
    "src/services/html/htmlGenerator.js~HTMLGenerator#options",
    "member"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgenerator#valuesservice",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html#instance-member-valuesService",
    "src/services/html/htmlGenerator.js~HTMLGenerator#valuesService",
    "member"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgenerator#whenready",
    "class/src/services/html/htmlGenerator.js~HTMLGenerator.html#instance-method-whenReady",
    "src/services/html/htmlGenerator.js~HTMLGenerator#whenReady",
    "method"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgeneratoroptions",
    "typedef/index.html#static-typedef-HTMLGeneratorOptions",
    "src/services/html/htmlGenerator.js~HTMLGeneratorOptions",
    "typedef"
  ],
  [
    "src/services/html/htmlgenerator.js~htmlgeneratorvaluesservice",
    "typedef/index.html#static-typedef-HTMLGeneratorValuesService",
    "src/services/html/htmlGenerator.js~HTMLGeneratorValuesService",
    "typedef"
  ],
  [
    "src/services/html/index.js",
    "file/src/services/html/index.js.html",
    "src/services/html/index.js",
    "file"
  ],
  [
    "src/services/http/http.js",
    "file/src/services/http/http.js.html",
    "src/services/http/http.js",
    "file"
  ],
  [
    "src/services/http/http.js~http#_logrequest",
    "class/src/services/http/http.js~HTTP.html#instance-method-_logRequest",
    "src/services/http/http.js~HTTP#_logRequest",
    "method"
  ],
  [
    "src/services/http/http.js~http#_logresponse",
    "class/src/services/http/http.js~HTTP.html#instance-method-_logResponse",
    "src/services/http/http.js~HTTP#_logResponse",
    "method"
  ],
  [
    "src/services/http/http.js~http#applogger",
    "class/src/services/http/http.js~HTTP.html#instance-member-appLogger",
    "src/services/http/http.js~HTTP#appLogger",
    "member"
  ],
  [
    "src/services/http/http.js~http#constructor",
    "class/src/services/http/http.js~HTTP.html#instance-constructor-constructor",
    "src/services/http/http.js~HTTP#constructor",
    "method"
  ],
  [
    "src/services/http/http.js~http#fetch",
    "class/src/services/http/http.js~HTTP.html#instance-method-fetch",
    "src/services/http/http.js~HTTP#fetch",
    "method"
  ],
  [
    "src/services/http/http.js~http#getcustomheadersfromrequest",
    "class/src/services/http/http.js~HTTP.html#instance-method-getCustomHeadersFromRequest",
    "src/services/http/http.js~HTTP#getCustomHeadersFromRequest",
    "method"
  ],
  [
    "src/services/http/http.js~http#getipfromrequest",
    "class/src/services/http/http.js~HTTP.html#instance-method-getIPFromRequest",
    "src/services/http/http.js~HTTP#getIPFromRequest",
    "method"
  ],
  [
    "src/services/http/http.js~http#logrequests",
    "class/src/services/http/http.js~HTTP.html#instance-member-logRequests",
    "src/services/http/http.js~HTTP#logRequests",
    "member"
  ],
  [
    "src/services/http/http.js~httpfetchoptions",
    "typedef/index.html#static-typedef-HTTPFetchOptions",
    "src/services/http/http.js~HTTPFetchOptions",
    "typedef"
  ],
  [
    "src/services/http/http.js~headers",
    "https://developer.mozilla.org/en-US/docs/Web/API/Headers",
    "src/services/http/http.js~Headers",
    "external"
  ],
  [
    "src/services/http/index.js",
    "file/src/services/http/index.js.html",
    "src/services/http/index.js",
    "file"
  ],
  [
    "src/services/http/responsesbuilder.js",
    "file/src/services/http/responsesBuilder.js.html",
    "src/services/http/responsesBuilder.js",
    "file"
  ],
  [
    "src/services/http/responsesbuilder.js~responsesbuilder#appconfiguration",
    "class/src/services/http/responsesBuilder.js~ResponsesBuilder.html#instance-member-appConfiguration",
    "src/services/http/responsesBuilder.js~ResponsesBuilder#appConfiguration",
    "member"
  ],
  [
    "src/services/http/responsesbuilder.js~responsesbuilder#constructor",
    "class/src/services/http/responsesBuilder.js~ResponsesBuilder.html#instance-constructor-constructor",
    "src/services/http/responsesBuilder.js~ResponsesBuilder#constructor",
    "method"
  ],
  [
    "src/services/http/responsesbuilder.js~responsesbuilder#htmlpostmessage",
    "class/src/services/http/responsesBuilder.js~ResponsesBuilder.html#instance-method-htmlPostMessage",
    "src/services/http/responsesBuilder.js~ResponsesBuilder#htmlPostMessage",
    "method"
  ],
  [
    "src/services/http/responsesbuilder.js~responsesbuilder#json",
    "class/src/services/http/responsesBuilder.js~ResponsesBuilder.html#instance-method-json",
    "src/services/http/responsesBuilder.js~ResponsesBuilder#json",
    "method"
  ],
  [
    "src/services/http/responsesbuilder.js~responsesbuilderpostmessageoptions",
    "typedef/index.html#static-typedef-ResponsesBuilderPostMessageOptions",
    "src/services/http/responsesBuilder.js~ResponsesBuilderPostMessageOptions",
    "typedef"
  ],
  [
    "src/services/index.js",
    "file/src/services/index.js.html",
    "src/services/index.js",
    "file"
  ],
  [
    "src/typedef.js",
    "file/src/typedef.js.html",
    "src/typedef.js",
    "file"
  ],
  [
    "src/typedef.js~apiclientbase",
    "https://homer0.github.io/wootils/class/wootils/shared/apiClient.js~APIClient.html",
    "src/typedef.js~APIClientBase",
    "external"
  ],
  [
    "src/typedef.js~apiclientendpoints",
    "https://homer0.github.io/wootils/typedef/index.html#static-typedef-APIClientEndpoints",
    "src/typedef.js~APIClientEndpoints",
    "external"
  ],
  [
    "src/typedef.js~appconfiguration",
    "https://homer0.github.io/wootils/class/wootils/node/appConfiguration.js~AppConfiguration.html",
    "src/typedef.js~AppConfiguration",
    "external"
  ],
  [
    "src/typedef.js~controller",
    "typedef/index.html#static-typedef-Controller",
    "src/typedef.js~Controller",
    "typedef"
  ],
  [
    "src/typedef.js~environmentutils",
    "https://homer0.github.io/wootils/class/wootils/node/environmentUtils.js~EnvironmentUtils.html",
    "src/typedef.js~EnvironmentUtils",
    "external"
  ],
  [
    "src/typedef.js~errorhandler",
    "https://homer0.github.io/wootils/class/wootils/node/errorHandler.js~ErrorHandler.html",
    "src/typedef.js~ErrorHandler",
    "external"
  ],
  [
    "src/typedef.js~express",
    "https://expressjs.com/en/4x/api.html",
    "src/typedef.js~Express",
    "external"
  ],
  [
    "src/typedef.js~expressmiddleware",
    "http://expressjs.com/en/guide/using-middleware.html",
    "src/typedef.js~ExpressMiddleware",
    "external"
  ],
  [
    "src/typedef.js~expressnext",
    "typedef/index.html#static-typedef-ExpressNext",
    "src/typedef.js~ExpressNext",
    "typedef"
  ],
  [
    "src/typedef.js~expressrequest",
    "https://expressjs.com/en/4x/api.html#req",
    "src/typedef.js~ExpressRequest",
    "external"
  ],
  [
    "src/typedef.js~expressresponse",
    "https://expressjs.com/en/4x/api.html#res",
    "src/typedef.js~ExpressResponse",
    "external"
  ],
  [
    "src/typedef.js~expressresponse",
    "https://expressjs.com/en/4x/api.html#res",
    "src/typedef.js~ExpressResponse",
    "external"
  ],
  [
    "src/typedef.js~logger",
    "https://homer0.github.io/wootils/class/wootils/node/logger.js~Logger.html",
    "src/typedef.js~Logger",
    "external"
  ],
  [
    "src/typedef.js~middleware",
    "typedef/index.html#static-typedef-Middleware",
    "src/typedef.js~Middleware",
    "typedef"
  ],
  [
    "src/typedef.js~pathutils",
    "https://homer0.github.io/wootils/class/wootils/node/pathUtils.js~PathUtils.html",
    "src/typedef.js~PathUtils",
    "external"
  ],
  [
    "src/typedef.js~provider",
    "typedef/index.html#static-typedef-Provider",
    "src/typedef.js~Provider",
    "typedef"
  ],
  [
    "src/typedef.js~rootrequire",
    "https://homer0.github.io/wootils/function/index.html#static-function-rootRequire",
    "src/typedef.js~RootRequire",
    "external"
  ],
  [
    "src/utils/wrappers.js",
    "file/src/utils/wrappers.js.html",
    "src/utils/wrappers.js",
    "file"
  ]
]